repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1 # or any other specific version
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 22.3.0 # or any other specific version
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1 # or any other specific version
    hooks:
      - id: isort
        name: isort (python)
